### ISSUE TITLE
Can we run an example / test without token?

### ISSUE THREAD

**Issue by paulhybryant** [wechaty/wechaty-getting-started#158]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

Can we run an example / test without token?
I want to develop and test my code, before requesting the token to test with a real wechat account.

**Comment by huan** [comment]
Yes, you can run the example without token by using the Web Protocol, which you can run it locally.

## Using Web Protocol

In order to specify a Wechaty Puppet Provider, you need to set the `WECHATY_PUPPET` environment variable.

Set `WECHATY_PUPPET` to `wechaty-puppet-puppeteer` or `wechaty-puppet-wechat4u` will let Wechaty using Web Protocol. Please confirm that your WeChat account can log in on Web WeChat before using them.

```sh
export WECHATY_PUPPET=wechaty-puppet-puppeteer
ts-node example/ding-dong-bot.ts
```

**Comment by paulhybryant** [comment]
No, my wechat account cannot log in on Web wechat. That is why I want to use the ipad protocol (which requires a token).
But I want to test my code a bit before I apply for a token as it expires in 15 days. I want to test my code first and do some testing with the wechat account using the token.

**Comment by huan** [comment]
If your WeChat account can not use Web Protocol, then you will have to use one of the Puppet Services.

You can apply a short-term TOKEN for free, learn more from https://wechaty.js.org/docs/puppet-services/

**Comment by paulhybryant** [comment]
OK. I will do that. Thanks.
