### ISSUE TITLE
Re-record the getting started guide video

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-getting-started#17]
And update the Blog with the new Youtube link.

**Comment by lijiarui** [comment]
duplicate with #35

**Comment by lijiarui** [comment]
Only this one left for a more clear One page wechaty introduction in #23 
And tutorial link as follows:

https://v.qq.com/x/page/k0726ho4rce.html

**Comment by zixia** [comment]
The video LGTM, you can use it for the getting started tutorial.

And I'd like to suggest you publish a new Tutorial Blog instead of modifying the old one because the old one can be used for the Wechaty version v0.14 or below.

As the new tutorial is published, you can add a **Update** message in the old tutorial, link to your new tutorial for Wechaty version 0.18 or above.

**Comment by huan** [comment]
Close this issue because it is getting to be 1 year old.
