### ISSUE TITLE
Moving the Official Wechaty Examples over

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-getting-started#21]
Is it a good idea to move the Official Wechaty Examples from https://github.com/Chatie/wechaty/tree/master/examples to here? 

Those example, cannot be used out of the box, due to the relative-path importing. 
Moving them over here will eliminate one more unnecessary step for new developers/users to try out Wechaty. 

At the very least, please move the ding-dong-bot over, and give example in README how to start the ding-dong ***typescript*** bot. 

And please move hot-import-bot example over as well, as I wasn't even able to make it run -- https://github.com/Chatie/wechaty/issues/1222

Thx

**Comment by suntong** [comment]
I think all of the following bots belong here, thus hope at least these are moved over. 

- ding-dong-bot
- media-file-bot
- hot-import-bot
- gist-bot

**Comment by zixia** [comment]
Thanks for the suggestion and I feels it's a very good idea.

The only thing we need to take care is to keep this starter repo from to be complicated: it has to be the simplest because we must try our best to make the studying curve smooth for the beginners.

I'll keep this open and think about it later.

**Comment by suntong** [comment]
Good point to keep this starter repo from to be complicated. In that case, I'm thinking at least these samples should be moved over:

- ding-dong-bot
- media-file-bot
- hot-import-bot

Because, after all, we need to do something in the end right? Having as many working-out-of-the-box examples as possible will definitely be an asset, that why I was including `gist-bot` previously because for people that aim big projects, that'll be a better start. 

Any way, still my 2c, 
your call.

**Comment by zixia** [comment]
We had just added those examples because, after some time of thinking, I feel it's necessary to add them as vanilla javascript example.

In order to keep things simple, we just put the examples in the subdirectory of the examples/ directory, and it can just run out-of-the-box.

Thank you for purposing this, and keep trying to use our hot-import-bot! :)

**Comment by zixia** [comment]
@suntong Now we have all the Wechaty examples in this repository, you can have a look on it at <https://github.com/Chatie/wechaty-getting-started/tree/master/>

There would be one more job left: the README should be better written. Would you like to write a README for the Examples List Directory? It would be fantastic if you could because you will have a better view than me.

**Comment by suntong** [comment]
I'm honored, however I'll be very busy for the next two weeks. Will try find sometime after that. 
Let me leave this open to remind me...

**Comment by zixia** [comment]
Thank you very much for accepting my invitation!

Please take your time and no rush, and looking forward to your documentation PR!

**Comment by zixia** [comment]
ping @suntong 

Did you get time recently?

**Comment by zixia** [comment]
No problem, just want to know your schedule.

Let's get iback to it again on September.

**Comment by suntong** [comment]
Yeah, finally got some free time this weekend, however, my new cheap Android phone is acting up and not letting me to install the Google Service and App Store. I've spent the whole weekend fighting it, but up till now it is stilling winning. 

Anyway, will try to see if I can find some free time next weekend ...

**Comment by zixia** [comment]
Okay. And good luck to you for your next fighting with your Android! :laughing:

**Comment by suntong** [comment]
I've done the English part (see https://github.com/Chatie/wechaty-getting-started/pull/54) and have left out the Chinese part, as I'm really not good at typing Chinese. 

Please review. As for the Chinese, I don't think word-for-word translating my description is necessary, as the writer might have a better view than me, :)

cheers

**Comment by huan** [comment]
Close this issue because all tasks had been done perfectly.
