### ISSUE TITLE
gist-bot/  将不同的处理模块分散到不同文件里面的代码例子 运行后报错

### ISSUE THREAD

**Issue by god-bless-me** [wechaty/wechaty-getting-started#79]
gist-bot/将不同的处理模块分散到不同文件里面的代码例子,这个运行后报错 .采用的是最新的npm编译的代码。报错内容如下：
![image](https://user-images.githubusercontent.com/13415085/53713700-c1d4cf80-3e86-11e9-96bb-77d793925b44.png)

**Comment by lijiarui** [comment]
Important：Please file the issue follow the template, or we won't help you to solve the problem.
---


## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer:

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer:

- What is your node version? (run `node --version`)
Answer:

- What os are you using
Answer:

## 2. Describe the bug
Give a clear and concise description of what the bug is.

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

Steps to reproduce the behavior:
1. run '...'
2. ...
3. ...

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.


## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context
Add any other context about the problem here.

[bug]

**Comment by lijiarui** [comment]
I will close this issue, if you have any questions, please file a new one based on our template
